server:
  port: 8001

spring:
  application:
    name: eureka-discovery-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"