server:
#  port: 8081
  port: 0

spring:
  application:
    name: issuing-bank
  datasource:
    url: jdbc:postgresql://localhost:5434/ib_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: ib_schema
      connection-init-sql: create schema if not exists ib_schema
      connection-timeout: 10000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6377


app:
  redis:
    enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"