server:
  port: 8002

spring:
  application:
    name: eureka-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
